server {
    listen       80;
    server_name  localhost;

    root   /hexo/public;
    index  index.html index.htm;

    # 处理 Hexo 的 clean URLs
    location / {
        try_files $uri $uri/ =404;
    }

    # 禁止直接访问隐藏文件
    location ~ /\. {
        deny all;
    }
}
